// serverless-vue/src/pages/AuthPage/index.vue
<template>
    <div>
        <form @submit.prevent="login">
            <label>Username: </label>
            <input type="text" v-model="username" />
            <br />
            <label>Password: </label>
            <input type="password" v-model="password" />
            <br />
            <button type="submit">Login</button>
        </form>

        <form @submit.prevent="signup">
            <label>Username: </label>
            <input type="text" v-model="username" />
            <br />
            <label>Password: </label>
            <input type="password" v-model="password" />
            <br />
            <label>Email: </label>
            <input type="text" v-model="email" />
            <br />
            <label>First name: </label>
            <input type="text" v-model="first_name" />
            <br />
            <label>Last name: </label>
            <input type="text" v-model="last_name" />
            <br />
            <button type="submit">Sign Up</button>
        </form>
    </div>
</template>
  
<script>
import { loginRest, signupRest } from './api'

export default {
    data() {
        return {
            username: '',
            password: '',
            email: '',
            first_name: '',
            last_name: '',
        }
    },
    methods: {
        login() {
            loginRest(this.username, this.password)
            .then(response => this.$emit('onAuth', { ...response.data, secret: this.password } ))
            .catch(error => console.log('Login error', error));
        },
        signup() {
            signupRest(this.username, this.password, this.email, this.first_name, this.last_name)
            .then(response => this.$emit('onAuth', { ...response.data, secret: this.password } ))
            .catch(error => console.log('Sign up error', error));
        },
    },
}
</script>

// client-react/src/app/authPage/index.js
import { useState } from "react";
import axios from "axios";

const AuthPage = (props) => {
  const [username, setUsername] = useState();
  const [secret, setSecret] = useState();
  const [email, setEmail] = useState();
  const [first_name, setFirstName] = useState();
  const [last_name, setLastName] = useState();

  const onLogin = (e) => {
    e.preventDefault();
    axios
      .post("http://localhost:3001/login", { username, secret })
      .then((r) => props.onAuth({ ...r.data, secret })) // NOTE: over-ride secret
      .catch((e) => console.log(JSON.stringify(e.response.data)));
  };

  const onSignup = (e) => {
    e.preventDefault();
    axios
      .post("http://localhost:3001/signup", {
        username,
        secret,
        email,
        first_name,
        last_name,
      })
      .then((r) => props.onAuth({ ...r.data, secret })) // NOTE: over-ride secret
      .catch((e) => console.log(JSON.stringify(e.response.data)));
  };

  return (
    <div style={{ margin: "24px" }}>
      {/* Login Form */}
      <form onSubmit={onLogin}>
        <h3>Login</h3>
        <label>
          Username:
          <input
            type="text"
            name="username"
            onChange={(e) => setUsername(e.target.value)}
          />
        </label>
        <br />
        <label>
          Secret:
          <input
            type="password"
            name="secret"
            onChange={(e) => setSecret(e.target.value)}
          />
        </label>
        <br />
        <input type="submit" value="Login" />
      </form>
      {/* Sign Up Form */}
      <form onSubmit={onSignup}>
        <h3>or Sign Up</h3>
        <label>
          Username:
          <input
            type="text"
            name="username"
            onChange={(e) => setUsername(e.target.value)}
          />
        </label>
        <br />
        <label>
          Password:
          <input
            type="password"
            name="secret"
            onChange={(e) => setSecret(e.target.value)}
          />
        </label>
        <br />
        <label>
          Email:
          <input
            type="text"
            name="email"
            onChange={(e) => setEmail(e.target.value)}
          />
        </label>
        <br />
        <label>
          First name:
          <input
            type="text"
            name="first_name"
            onChange={(e) => setFirstName(e.target.value)}
          />
        </label>
        <br />
        <label>
          Last name:
          <input
            type="text"
            name="last_name"
            onChange={(e) => setLastName(e.target.value)}
          />
        </label>
        <br />
        <input type="submit" value="Sign Up" />
      </form>
    </div>
  );
};

export default AuthPage;
