// client-react/src/app/index.js
import { useState } from "react";

import AuthPage from "./authPage";
import ChatsPage from "./chatsPage";

function App() {
  const [user, setUser] = useState();

  if (!user) {
    return <AuthPage onAuth={(user) => setUser(user)} />;
  } else {
    return <ChatsPage user={user} />;
  }
}

export default App;

// serverless-vue/src/App.vue
<script setup>
import AuthPage from './pages/AuthPage/index.vue'
import ChatsPage from './pages/ChatsPage/index.vue'
</script>

<template>
  <AuthPage v-if="!user" @onAuth="handleAuth" />
  <ChatsPage v-else v-bind:username="user.username" v-bind:secret="user.secret" />
</template>

<script>
export default {
  data() {
    return {
      user: undefined,
    }
  },
  methods: {
    handleAuth(user) {
      this.user = user;
    },
  },
}
</script>
